Fix repository URL in package.json
zowe/zowe-cli-mq-plugin pull request #48
Opened 2023-04-03 20:57 UTC by t1m0thyj

Q: Is it worth adding a changelog update and publishing a patch release to fix this?

2023-04-03 21:06 UTC, gejohnston approved these changes

2023-04-03 21:08 UTC, gejohnston commented
Its probably a lot of overhead for such a small change, but it would be alarming for someone to follow this link  and hit a dead-end indicating that the product does not exist anymore.

2023-04-04 11:59 UTC, zFernand0 requested changes
I kind of agree with Gene here.
Could we update the changelog?

2023-04-04 12:22 UTC, awharn approved these changes

2023-04-04 13:16 UTC, zFernand0 approved these changes

2023-04-04 13:33 UTC, traeok approved these changes

2023-04-04 13:43 UTC, merged