updating versioning
zowe/zowe-cli-mq-plugin pull request #52
Opened 2023-05-05 20:10 UTC by ATorrise

Action | Description
-- | --									
#6 | [update all workflows to remove deprecation warnings](https://github.com/zowe/zowe-cli-web-help-generator/pull/35/files), [octorelease updates](https://github.com/zowe/zowe-cli/pull/1712)										
#7 | remove Node 14 from workflow matrix

2023-05-08 15:12 UTC, zFernand0 requested changes
left some comments.
hopefully nothing major though

2023-05-08 15:12 UTC, zFernand0 commented on .github/workflows/changelog.yml
Can we update `awharn/check_changelog_action@v0.0.2` to `v1`?

2023-05-08 15:12 UTC, zFernand0 commented on .github/workflows/codeql.yml
> -      uses: github/codeql-action/init@v1
can we also update `analyze` to `v2`

2023-05-08 15:12 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
don't forget to remove the node 14 version from the matrix.
And now that 14 will be gone, we should be good to remove the `Update NPM` step since node 16 now bundles with `npm@8`

2023-05-09 15:34 UTC, t1m0thyj requested changes

2023-05-09 15:34 UTC, t1m0thyj commented on .github/workflows/zowe-cli-plugin.yml
> -
We want to keep this step - updating npm to v8 isn't necessary with Node 16 and newer, but we still want to keep our dependencies up to date.

2023-05-09 15:34 UTC, t1m0thyj commented on .github/workflows/zowe-cli-plugin.yml
> -
The `zowe-actions/octorelease-script@master` should be `zowe-actions/octorelease/script@v1`

2023-05-10 15:19 UTC, zFernand0 requested changes

2023-05-10 15:19 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
> +        script: npmUpdate
sorry for the confusion, this step should be in the previous job 😢 
ideally right after `npm ci` (where it was) 😋

2023-05-11 16:31 UTC, zFernand0 approved these changes
LGTM! 😋

2023-05-11 17:33 UTC, t1m0thyj approved these changes

2023-05-11 17:33 UTC, merged